name: Tests

on:
  pull_request:
    branches: [main, master]
    types: [opened, synchronize, reopened]

jobs:
  test:
    uses: kenshin579/actions/.github/workflows/unit-test-go.yml@main
    with:
      go_version: '1.23'
      run_unit_tests: true
      run_integration_tests: false
      unit_test_args: '-v'
      coverage_enabled: true
      post_comment: true
